repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '2.2.1'
    hooks:
      # Validate poetry configuration.
      - id: poetry-check
      # Update the lock file.
      - id: poetry-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.6
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
