# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rivian/parallax/proto/device_table.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'rivian/parallax/proto/device_table.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(rivian/parallax/proto/device_table.proto\x12\x1crivian.parallax.device_table\"\xfc\x06\n\x10VasKeyperDevices\x12I\n\x07\x66ield_1\x18\x01 \x01(\x0b\x32\x38.rivian.parallax.device_table.VasKeyperDevices.Unmapped1\x12\x45\n\x06\x64\x65vice\x18\x02 \x01(\x0b\x32\x35.rivian.parallax.device_table.VasKeyperDevices.Device\x12O\n\x0b\x63redentials\x18\x03 \x01(\x0b\x32:.rivian.parallax.device_table.VasKeyperDevices.Credentials\x1a-\n\tUnmapped1\x12\x14\n\x07\x66ield_3\x18\x03 \x01(\x05H\x00\x88\x01\x01\x42\n\n\x08_field_3\x1a\xa6\x01\n\x06\x44\x65vice\x12\x1f\n\x12mapped_identity_id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04hrid\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x17\n\npairing_id\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x14\n\x07\x66ield_5\x18\x05 \x01(\x05H\x03\x88\x01\x01\x42\x15\n\x13_mapped_identity_idB\x07\n\x05_hridB\r\n\x0b_pairing_idB\n\n\x08_field_5\x1a\xac\x03\n\x0b\x43redentials\x12M\n\x04info\x18\x01 \x01(\x0b\x32?.rivian.parallax.device_table.VasKeyperDevices.Credentials.Info\x12K\n\x03\x62le\x18\x05 \x01(\x0b\x32>.rivian.parallax.device_table.VasKeyperDevices.Credentials.Ble\x12\x15\n\x08key_type\x18\t \x01(\x05H\x00\x88\x01\x01\x12\x13\n\x06\x61\x63tive\x18\n \x01(\x08H\x01\x88\x01\x01\x1ah\n\x04Info\x12\x0e\n\x01\x61\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x0e\n\x01\x63\x18\x04 \x01(\x05H\x01\x88\x01\x01\x12\x13\n\x06status\x18\x05 \x01(\x05H\x02\x88\x01\x01\x12\x0e\n\x01\x62\x18\x06 \x01(\x05H\x03\x88\x01\x01\x42\x04\n\x02_aB\x04\n\x02_cB\t\n\x07_statusB\x04\n\x02_b\x1aS\n\x03\x42le\x12\x16\n\tdevice_id\x18\x01 \x01(\x0cH\x00\x88\x01\x01\x12\x17\n\ncredential\x18\x02 \x01(\x0cH\x01\x88\x01\x01\x42\x0c\n\n_device_idB\r\n\x0b_credentialB\x0b\n\t_key_typeB\t\n\x07_activeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rivian.parallax.proto.device_table_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VASKEYPERDEVICES']._serialized_start=75
  _globals['_VASKEYPERDEVICES']._serialized_end=967
  _globals['_VASKEYPERDEVICES_UNMAPPED1']._serialized_start=322
  _globals['_VASKEYPERDEVICES_UNMAPPED1']._serialized_end=367
  _globals['_VASKEYPERDEVICES_DEVICE']._serialized_start=370
  _globals['_VASKEYPERDEVICES_DEVICE']._serialized_end=536
  _globals['_VASKEYPERDEVICES_CREDENTIALS']._serialized_start=539
  _globals['_VASKEYPERDEVICES_CREDENTIALS']._serialized_end=967
  _globals['_VASKEYPERDEVICES_CREDENTIALS_INFO']._serialized_start=754
  _globals['_VASKEYPERDEVICES_CREDENTIALS_INFO']._serialized_end=858
  _globals['_VASKEYPERDEVICES_CREDENTIALS_BLE']._serialized_start=860
  _globals['_VASKEYPERDEVICES_CREDENTIALS_BLE']._serialized_end=943
# @@protoc_insertion_point(module_scope)
