# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rivian/parallax/proto/gearguard_streaming.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'rivian/parallax/proto/gearguard_streaming.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/rivian/parallax/proto/gearguard_streaming.proto\x12#rivian.parallax.gearguard_streaming\"p\n\x19GearGuardStreamingConsent\x12G\n\x07\x63onsent\x18\x01 \x01(\x0e\x32\x31.rivian.parallax.gearguard_streaming.ConsentValueH\x00\x88\x01\x01\x42\n\n\x08_consent\"\xa6\x01\n\x1cGearGuardStreamingDailyLimit\x12H\n\x05limit\x18\x01 \x01(\x0e\x32\x34.rivian.parallax.gearguard_streaming.DailyLimitValueH\x00\x88\x01\x01\x12\x1d\n\x10limit_reset_time\x18\x02 \x01(\x03H\x01\x88\x01\x01\x42\x08\n\x06_limitB\x13\n\x11_limit_reset_time*\x8b\x01\n\x0c\x43onsentValue\x12\x18\n\x14\x43ONSENT_UNRECOGNIZED\x10\x00\x12\x15\n\x11\x43ONSENT_CONSENTED\x10\x01\x12\x19\n\x15\x43ONSENT_NOT_CONSENTED\x10\x02\x12\x1a\n\x16\x43ONSENT_NOT_APPLICABLE\x10\x03\x12\x13\n\x0f\x43ONSENT_UNKNOWN\x10\x04*x\n\x0f\x44\x61ilyLimitValue\x12\x1c\n\x18\x44\x41ILY_LIMIT_UNRECOGNIZED\x10\x00\x12\x19\n\x15\x44\x41ILY_LIMIT_UNDEFINED\x10\x01\x12\x17\n\x13\x44\x41ILY_LIMIT_NOT_HIT\x10\x02\x12\x13\n\x0f\x44\x41ILY_LIMIT_HIT\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rivian.parallax.proto.gearguard_streaming_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONSENTVALUE']._serialized_start=372
  _globals['_CONSENTVALUE']._serialized_end=511
  _globals['_DAILYLIMITVALUE']._serialized_start=513
  _globals['_DAILYLIMITVALUE']._serialized_end=633
  _globals['_GEARGUARDSTREAMINGCONSENT']._serialized_start=88
  _globals['_GEARGUARDSTREAMINGCONSENT']._serialized_end=200
  _globals['_GEARGUARDSTREAMINGDAILYLIMIT']._serialized_start=203
  _globals['_GEARGUARDSTREAMINGDAILYLIMIT']._serialized_end=369
# @@protoc_insertion_point(module_scope)
