# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rivian/parallax/proto/geofence.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'rivian/parallax/proto/geofence.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$rivian/parallax/proto/geofence.proto\x12\x18rivian.parallax.geofence\"\xa5\x01\n\x11\x46\x61voriteGeofences\x12\x46\n\x08geofence\x18\x01 \x03(\x0b\x32\x34.rivian.parallax.geofence.FavoriteGeofences.Geofence\x1aH\n\x08Geofence\x12\x14\n\x07\x66ield_1\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x11\n\x04name\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\n\n\x08_field_1B\x07\n\x05_nameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rivian.parallax.proto.geofence_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FAVORITEGEOFENCES']._serialized_start=67
  _globals['_FAVORITEGEOFENCES']._serialized_end=232
  _globals['_FAVORITEGEOFENCES_GEOFENCE']._serialized_start=160
  _globals['_FAVORITEGEOFENCES_GEOFENCE']._serialized_end=232
# @@protoc_insertion_point(module_scope)
