# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rivian/parallax/proto/parallax.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'rivian/parallax/proto/parallax.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$rivian/parallax/proto/parallax.proto\x12\x18rivian.parallax.parallax\"\xd7\x01\n\tHeartbeat\x12\x14\n\x07\x66ield_1\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12;\n\x04time\x18\x02 \x01(\x0b\x32-.rivian.parallax.parallax.Heartbeat.Timestamp\x12>\n\x07\x66ield_3\x18\x03 \x01(\x0b\x32-.rivian.parallax.parallax.Heartbeat.Timestamp\x1a+\n\tTimestamp\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x12\r\n\x05nanos\x18\x02 \x01(\x05\x42\n\n\x08_field_1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rivian.parallax.proto.parallax_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEARTBEAT']._serialized_start=67
  _globals['_HEARTBEAT']._serialized_end=282
  _globals['_HEARTBEAT_TIMESTAMP']._serialized_start=227
  _globals['_HEARTBEAT_TIMESTAMP']._serialized_end=270
# @@protoc_insertion_point(module_scope)
