# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rivian/parallax/proto/user_passcodes.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'rivian/parallax/proto/user_passcodes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*rivian/parallax/proto/user_passcodes.proto\x12\x1erivian.parallax.user_passcodes\"a\n\x11\x44riveAuthPasscode\x12\x42\n\x05state\x18\x01 \x01(\x0e\x32..rivian.parallax.user_passcodes.DriveAuthStateH\x00\x88\x01\x01\x42\x08\n\x06_state*c\n\x0e\x44riveAuthState\x12 \n\x1c\x44RIVE_AUTH_STATE_UNSPECIFIED\x10\x00\x12\x17\n\x13\x44RIVE_AUTH_DISABLED\x10\x01\x12\x16\n\x12\x44RIVE_AUTH_ENABLED\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rivian.parallax.proto.user_passcodes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DRIVEAUTHSTATE']._serialized_start=177
  _globals['_DRIVEAUTHSTATE']._serialized_end=276
  _globals['_DRIVEAUTHPASSCODE']._serialized_start=78
  _globals['_DRIVEAUTHPASSCODE']._serialized_end=175
# @@protoc_insertion_point(module_scope)
