# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rivian/parallax/proto/vehicle_access.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rivian/parallax/proto/vehicle_access.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*rivian/parallax/proto/vehicle_access.proto\x12\x1erivian.parallax.vehicle_access\"\x15\n\x13PassiveEntrySetting\"\xd5\x01\n\x11PassiveEntryState\x12)\n\x1c\x61llow_bluetooth_while_in_ccc\x18\x01 \x01(\x08H\x00\x88\x01\x01\x12Y\n\x16\x63\x63\x63_passive_permission\x18\x02 \x01(\x0e\x32\x34.rivian.parallax.vehicle_access.CccPassivePermissionH\x01\x88\x01\x01\x42\x1f\n\x1d_allow_bluetooth_while_in_cccB\x19\n\x17_ccc_passive_permission*\xa7\x01\n\x14\x43\x63\x63PassivePermission\x12&\n\"CCC_PASSIVE_PERMISSION_UNSPECIFIED\x10\x00\x12\x1e\n\x1a\x43\x43\x43_PASSIVE_PERMISSION_SNA\x10\x01\x12\"\n\x1e\x43\x43\x43_PASSIVE_PERMISSION_ENABLED\x10\x02\x12#\n\x1f\x43\x43\x43_PASSIVE_PERMISSION_DISABLED\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rivian.parallax.proto.vehicle_access_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CCCPASSIVEPERMISSION']._serialized_start=318
  _globals['_CCCPASSIVEPERMISSION']._serialized_end=485
  _globals['_PASSIVEENTRYSETTING']._serialized_start=78
  _globals['_PASSIVEENTRYSETTING']._serialized_end=99
  _globals['_PASSIVEENTRYSTATE']._serialized_start=102
  _globals['_PASSIVEENTRYSTATE']._serialized_end=315
# @@protoc_insertion_point(module_scope)
